# Generated by Django 3.2.19 on 2023-05-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSave',
            fields=[
                ('DesignId', models.AutoField(primary_key=True, serialize=False)),
                ('DesignName', models.CharField(max_length=1000)),
                ('PhotoFileName', models.CharField(max_length=1000))
            ],
        ),
    ]
